import type { Ending } from '../../engine/types'

/**
 * 结局 = 状态评价函数。priority 越小越先判定，命中即停。
 * 设计原则：数值上的「失败」也要有叙事上的尊严。
 */
export const endings: Ending[] = [
  // ---- 即时结局（每回合判定） ----
  {
    id: 'soldSite',
    hint: '有人会为你的心血开出价码——如果它值得。',
    title: '卖站上岸',
    icon: 'flag',
    grade: 'S',
    priority: 10,
    when: 'immediate',
    conditions: { flag: 'soldSite', is: true },
    text: '第 {turn} 周，你签下了转让协议。账户里躺着一笔六位数的现金，而你脑子里已经在想下一个站做什么。上岸不是终点，是学会了游泳。',
  },
  {
    id: 'legend',
    hint: '传说不靠运气，靠把每一张风口都接住。',
    title: '传说中的那个人',
    icon: 'sparkle',
    grade: 'S',
    priority: 20,
    when: 'immediate',
    conditions: { stat: 'income', gte: 1000 },
    text: '日入 {stat.income} 刀。社群里新人问「真的有人做到日入千刀吗」，老人们会把你的故事讲一遍。你只用了 {turn} 周。',
  },
  {
    id: 'backToJob',
    hint: '回头路也是路。',
    title: '重返职场，但你已不同',
    icon: 'briefcase',
    grade: 'B',
    priority: 30,
    when: 'immediate',
    conditions: { flag: 'backToJob', is: true },
    text: '第 {turn} 周，你回到了工位。但这一次不一样——你见过凌晨四点的部署日志，赚到过属于自己的美元。副业的站还在跑，故事只是换了个讲法。',
  },
  {
    id: 'brokeButSkilled',
    hint: '钱包空了的时候，看看身上长出了什么。',
    title: '输了钱包，赢了本事',
    icon: 'book',
    grade: 'C',
    priority: 40,
    when: 'immediate',
    conditions: {
      all: [
        { stat: 'cash', lte: 0 },
        { any: [{ stat: 'seo', gte: 40 }, { stat: 'product', gte: 50 }] },
      ],
    },
    text: '第 {turn} 周，存款见底，你不得不按下暂停键。但你带走了完整的建站、SEO 和产品功夫——下一次出发，你不再是新手。这一课很贵，但值。',
  },
  {
    id: 'broke',
    hint: '弹药是有限的。',
    title: '弹尽粮绝',
    icon: 'skull',
    grade: 'D',
    priority: 41,
    when: 'immediate',
    conditions: { stat: 'cash', lte: 0 },
    text: '第 {turn} 周，余额归零。你删掉了服务器，保留了域名——万一哪天，还想再来一次呢。',
  },
  {
    id: 'quitBeforeDawn',
    hint: '最难熬的，是快亮的时候。',
    title: '在黎明前放弃',
    icon: 'moon',
    grade: 'C',
    priority: 50,
    when: 'immediate',
    conditions: { all: [{ stat: 'mood', lte: 0 }, { stat: 'income', gte: 1 }] },
    text: '第 {turn} 周，你心力耗尽，停掉了一切。讽刺的是，网站其实已经开始赚钱了。多年以后你偶尔会想：如果那时候再撑一个月呢？',
  },
  {
    id: 'burnout',
    hint: '别忘了照顾屏幕里那个小人。',
    title: '心态崩了',
    icon: 'mood',
    grade: 'D',
    priority: 51,
    when: 'immediate',
    conditions: { stat: 'mood', lte: 0 },
    text: '第 {turn} 周，你在一个普通的下午关掉了所有窗口，卸载了监控 App。不是所有故事都有高潮，有些故事教会你的是：先照顾好自己。',
  },

  {
    id: 'agencyBoss',
    hint: '手艺接得多了，会有人劝你把它变成生意。',
    title: '外包工作室老板',
    icon: 'briefcase',
    grade: 'B',
    priority: 32,
    when: 'immediate',
    conditions: { flag: 'agencyBoss', is: true },
    text: '第 {turn} 周，你成了三个人的老板。没有睡后收入，但有稳稳的现金流和喊你「哥」的实习生。出海站还在跑，成了你招牌上最亮的那行字——人生的岔路，未必是弯路。',
  },

  // ---- 终局结算（回合耗尽时判定） ----
  {
    id: 'communityLight',
    hint: '被看见之后，也让别人被看见。',
    title: '圈子里的那盏灯',
    icon: 'sparkle',
    grade: 'A',
    priority: 95,
    when: 'final',
    conditions: {
      all: [{ flag: 'famous', is: true }, { flag: 'audience', is: true }, { stat: 'income', gte: 5 }],
    },
    text: '两年，日入 {stat.income} 刀——不是圈里最高的，但你的帖子被新人一遍遍翻出来读。有人靠你的复盘赚到了第一刀，跑来谢你。你活成了自己出发时想遇到的那个人。',
  },
  {
    id: 'momLeader',
    hint: '你的用户，也许就在你每天的生活里。',
    title: '妈妈圈的主理人',
    icon: 'mood',
    grade: 'A',
    priority: 90,
    when: 'final',
    conditions: { all: [{ flag: 'momLeader', is: true }, { stat: 'income', gte: 3 }] },
    text: '两年，日入 {stat.income} 刀。但更值钱的是那个几千人的妈妈社群——你把「带娃的碎片时间」织成了一张网。当年那个想挣回名字的人，如今是大家口中的「主理人本人」。',
  },
  {
    id: 'townPioneer',
    hint: '小城会记得第一个出发的人。',
    title: '县城第一站长',
    icon: 'compass',
    grade: 'A',
    priority: 91,
    when: 'final',
    conditions: { all: [{ flag: 'townMentor', is: true }, { stat: 'income', gte: 5 }] },
    text: '两年，日入 {stat.income} 刀，全县独一份的职业。图书馆的「站长角」已经有七个人，最小的在读初二。这座没人聊出海的城市，因为你有了海的方向。',
  },
  {
    id: 'gradIndie',
    hint: '有一种毕业答辩，答的是自己的产品。',
    title: '没投过一份简历',
    icon: 'book',
    grade: 'A',
    priority: 92,
    when: 'final',
    conditions: { all: [{ flag: 'gradFree', is: true }, { stat: 'income', gte: 3 }] },
    text: '日入 {stat.income} 刀。同学们在期盼转正的年纪，你已经给自己发了两年工资。毕业相册里你的一栏写着：自由职业者，雇主——自己。',
  },
  {
    id: 'salaryFree',
    hint: '让睡后收入超过当年的日薪。',
    title: '工资自由',
    icon: 'income',
    grade: 'A',
    priority: 100,
    when: 'final',
    conditions: { stat: 'income', gte: 100 },
    text: '两年，日入 {stat.income} 刀，稳稳超过了当年的工资。你没有暴富，但你拿回了自己的时间——这才是当初辞职时真正想要的东西。',
  },
  {
    id: 'steadyTen',
    hint: '细水长流地走完两年。',
    title: '十刀俱乐部',
    icon: 'trophy',
    grade: 'A',
    priority: 110,
    when: 'final',
    conditions: { stat: 'income', gte: 10 },
    text: '两年，日入 {stat.income} 刀。不够辞职炫耀，但每天睁眼就有奶茶钱和饭钱。更重要的是：这台机器是你亲手搭的，而它还在长大。',
  },
  {
    id: 'oneDollarLine',
    hint: '从零到一，走完就赢了一半人。',
    title: '日入一刀，人生分界',
    icon: 'cash',
    grade: 'B',
    priority: 120,
    when: 'final',
    conditions: { stat: 'income', gte: 1 },
    text: '两年，日入 {stat.income} 刀。别人看是笑话，你知道是分界线：从零到一你已经走完了,剩下的只是重复和放大。故事未完待续。',
  },
  {
    id: 'glimmer',
    hint: '哪怕只有一点点。',
    title: '微光',
    icon: 'sparkle',
    grade: 'C',
    priority: 130,
    when: 'final',
    conditions: { stat: 'income', gt: 0 },
    text: '两年，日入 {stat.income} 刀。收入卑微得不好意思说出口，但后台里每一个真实用户都在提醒你：有微光，就不算黑夜。',
  },
  {
    id: 'expensiveLesson',
    hint: '有些学费不白交。',
    title: '两年学费',
    icon: 'book',
    grade: 'C',
    priority: 140,
    when: 'final',
    conditions: { any: [{ stat: 'seo', gte: 40 }, { stat: 'product', gte: 50 }, { stat: 'eng', gte: 60 }] },
    text: '两年过去，网站没赚到钱。但你身上多了一整套别人拿不走的本事。这两年不是弯路，是学费——只是缴费的方式比较特别。',
  },
  {
    id: 'longDream',
    hint: '至少要真的试过。',
    title: '一场大梦',
    icon: 'moon',
    grade: 'D',
    priority: 150,
    when: 'final',
    conditions: { all: [] },
    text: '两年过去，一切好像回到了原点。但深夜里你偶尔还会打开那个再也不更新的站——至少你真的试过。大多数人，连试都没试过。',
  },
]
