import type { EventCard } from '../../engine/types'

/** 内容扩充：通用日常/命运/风口补充池 */
export const extraEvents: EventCard[] = [
  // ---------- 日常 ----------
  {
    id: 'freeTierEnds',
    pool: 'daily',
    title: '白嫖到期',
    text: '云服务商发来邮件：你的免费额度下月到期。',
    valence: -1,
    cooldown: 30,
    conditions: { flag: 'siteLive', is: true },
    choices: [
      { text: '交钱，服务不能停', effects: [{ stat: 'cash', add: -150 }], resultText: '独立开发的第一课：免费的东西都有账单，只是晚点到。' },
      { text: '花一晚迁移到更便宜的方案', effects: [{ stat: 'mood', add: -2 }, { stat: 'dev', add: 2 }], resultText: '折腾到凌晨三点，账单归零。你的运维技能又厚了一层。' },
    ],
  },
  {
    id: 'tutorialDejavu',
    pool: 'daily',
    title: '视频里的坑',
    text: '刷到一个建站教程，里面讲的坑你三个月前刚亲自踩过一遍。',
    valence: 1,
    cooldown: 15,
    conditions: { flag: 'siteLive', is: true },
    choices: [
      { text: '会心一笑', effects: [{ stat: 'mood', add: 3 }], resultText: '原来你已经走到可以笑着回头看的地方了。' },
    ],
  },
  {
    id: 'copycat',
    pool: 'daily',
    title: '被抄了',
    text: '有人像素级复刻了你的站，连文案里的错别字都没改。',
    valence: -1,
    once: true,
    conditions: { stat: 'income', gte: 1 },
    choices: [
      { text: '发帖挂他', effects: [{ stat: 'mood', add: 2 }, { flag: 'vocal', value: true }], resultText: '帖子火了，评论一边倒。流量反而涨了一点——黑红也是红。' },
      { text: '不理他，加速迭代', effects: [{ stat: 'product', add: 3 }], resultText: '他能抄你的昨天，抄不了你的明天。' },
    ],
  },
  {
    id: 'firstGscCurve',
    pool: 'daily',
    title: '第一条曲线',
    text: 'Search Console 的展示量图表上，第一次出现了一条肉眼可见的上升线。',
    valence: 1,
    once: true,
    conditions: { flag: 'siteLive', is: true },
    choices: [
      { text: '截图存档', effects: [{ stat: 'mood', add: 5 }], resultText: '这条歪歪扭扭的小线，是互联网第一次对你点头。' },
    ],
  },
  {
    id: 'midnightIdea',
    pool: 'daily',
    title: '凌晨的灵感',
    text: '躺下十分钟，一个绝妙的功能点突然砸中你。',
    valence: 0,
    cooldown: 12,
    choices: [
      { text: '爬起来干', effects: [{ stat: 'product', add: 3 }, { stat: 'mood', add: -2 }], resultText: '干到四点。第二天看，嗯……有一半是真的妙。' },
      { text: '记在备忘录里睡觉', effects: [{ stat: 'mood', add: 2 }], resultText: '早上打开备忘录：「做那个！很重要！」……哪个？' },
    ],
  },
  {
    id: 'firstUnsub',
    pool: 'daily',
    title: '第一个退订',
    text: '邮件列表迎来了第一个退订用户，理由栏写着「内容不是我想要的」。',
    valence: -1,
    once: true,
    conditions: { stat: 'income', gt: 0 },
    choices: [
      { text: '盯着那行字看了很久', effects: [{ stat: 'mood', add: -3 }, { stat: 'product', add: 1 }], resultText: '你没法让所有人满意。但你把「想要什么」三个字想了一路。' },
    ],
  },
  {
    id: 'domainSale',
    pool: 'daily',
    title: '域名大促',
    text: '注册商搞活动，首年九块九。你的购物车里已经躺了六个「以后会用到」的域名。',
    valence: 0,
    cooldown: 25,
    choices: [
      { text: '囤！都是未来的站', effects: [{ stat: 'cash', add: -120 }, { stat: 'mood', add: 2 }], resultText: '每个域名都是一个平行宇宙的自己。虽然大概率一个都不会做。' },
      { text: '忍住，先做好手里的', effects: [{ stat: 'mood', add: 1 }], resultText: '成年人的自律：关掉购物车，打开代码编辑器。' },
    ],
  },
  {
    id: 'userScreenshot',
    pool: 'daily',
    title: '用户的截图',
    text: '有用户在推特晒出用你的工具做出来的成果，还圈了你。',
    valence: 1,
    cooldown: 12,
    conditions: { stat: 'income', gt: 0 },
    choices: [
      { text: '转发 + 感谢', effects: [{ stat: 'mood', add: 4 }], resultText: '做产品最上头的瞬间：别人用你造的东西，造出了他们的东西。' },
    ],
  },
  {
    id: 'catKeyboard',
    pool: 'daily',
    title: '猫的贡献',
    text: '你离开座位倒水的功夫，猫在键盘上睡着了。半篇稿子变成了乱码。',
    valence: -1,
    cooldown: 20,
    choices: [
      { text: '算了，它睡得很香', effects: [{ stat: 'mood', add: -2 }], resultText: '你重写了那半篇。写得比第一遍还好一点，气人。' },
    ],
  },
  {
    id: 'newBook',
    pool: 'daily',
    title: '快递到了',
    text: '下单的那本《SEO 实战》到了，塑封还没拆，上一本也还没看完。',
    valence: 0,
    cooldown: 18,
    choices: [
      { text: '今晚就读', effects: [{ stat: 'seo', add: 2 }], resultText: '读了三章，划了两页笔记。买书如山倒，读书如抽丝，但这次抽了。' },
    ],
  },
  {
    id: 'friendAsksSite',
    pool: 'daily',
    title: '老同学的请求',
    text: '「听说你会做网站？帮我搞一个呗，很简单的，就淘宝那种。」',
    valence: 0,
    cooldown: 22,
    choices: [
      { text: '接，赚个人情和外快', effects: [{ stat: 'cash', add: 800 }, { stat: 'mood', add: -3 }], resultText: '改了十一稿。他最后说「还是感觉第一版好」。' },
      { text: '委婉拒绝', effects: [{ stat: 'mood', add: 1 }], resultText: '「最近项目太紧啦。」你保住了整周的专注，和这段友谊。' },
    ],
  },
  {
    id: 'nightRadio',
    pool: 'daily',
    title: '深夜电台',
    text: '赶工的深夜，播客里两个陌生人聊着他们失败又重来的创业故事。',
    valence: 1,
    cooldown: 14,
    choices: [
      { text: '听完这期再睡', effects: [{ stat: 'mood', add: 4 }], resultText: '原来深夜亮着屏幕的，不止你一个人。' },
    ],
  },
  {
    id: 'greenDashboard',
    pool: 'daily',
    title: '全绿的一天',
    text: '收入、流量、排名，三个看板今天全是绿色的上升箭头。',
    valence: 1,
    cooldown: 16,
    conditions: { stat: 'income', gte: 1 },
    choices: [
      { text: '多刷新了几遍', effects: [{ stat: 'mood', add: 4 }], resultText: '你知道明天可能又红回去。所以今天的绿，要多看两眼。' },
    ],
  },
  {
    id: 'wireFee',
    pool: 'daily',
    title: '手续费刺客',
    text: '这个月的收入到账了，中间商们层层过手，到手少了一截。',
    valence: -1,
    cooldown: 20,
    conditions: { stat: 'income', gte: 3 },
    choices: [
      { text: '研究更优的收款链路', effects: [{ stat: 'cash', add: -80 }, { stat: 'product', add: 1 }], resultText: '折腾半天省下 1.2%。别小看它，这是复利。' },
    ],
  },
  {
    id: 'neighborKnock',
    pool: 'daily',
    title: '隔壁的敲墙声',
    text: '凌晨一点，你的机械键盘声引来了隔壁一记闷响。',
    valence: -1,
    cooldown: 18,
    choices: [
      { text: '换上静音轴/薄膜键盘', effects: [{ stat: 'cash', add: -200 }], resultText: '世界安静了。虽然手感差点意思，但邻里关系无价。' },
      { text: '改成白天干活', effects: [{ stat: 'mood', add: -2 }], resultText: '你试着做个白天人。第三天，又是凌晨一点。' },
    ],
  },
  {
    id: 'parkUncle',
    pool: 'daily',
    title: '公园大爷',
    text: '工作日下午你在公园散步，下棋的大爷抬头打量你：「小伙子，没上班啊？」',
    valence: 0,
    cooldown: 20,
    choices: [
      { text: '「我自己干。」', effects: [{ stat: 'mood', add: 2 }], resultText: '大爷点点头：「自己干好，自己干自由。」你俩都笑了。' },
      { text: '含糊过去', effects: [{ stat: 'mood', add: -2 }], resultText: '你发现最难解释的不是给大爷，是给自己。' },
    ],
  },
  {
    id: 'gemTool',
    pool: 'daily',
    title: '宝藏工具',
    text: '你发现了一个小众开发工具，恰好解决了折磨你两周的问题。',
    valence: 1,
    cooldown: 16,
    choices: [
      { text: '给作者写封感谢邮件', effects: [{ stat: 'dev', add: 2 }, { stat: 'mood', add: 2 }], resultText: '作者秒回：「你是第三个说谢谢的用户。」独立开发者都懂。' },
    ],
  },
  {
    id: 'offlineMeetup',
    pool: 'daily',
    title: '线下面基',
    text: '出海社群组织本城聚会，报名费一百八，都是网名认识的「老朋友」。',
    valence: 0,
    cooldown: 30,
    choices: [
      { text: '去！', effects: [{ stat: 'cash', add: -180 }, { stat: 'mood', add: 6 }, { stat: 'seo', add: 1 }], resultText: '聊到饭店打烊。原来头像后面都是活人，都在熬同一种夜。' },
      { text: '社恐发作，下次一定', effects: [{ stat: 'mood', add: -1 }], resultText: '你看着群里的合影，把「下次一定」打了出来又删掉。' },
    ],
  },
  {
    id: 'hundredFollowers',
    pool: 'daily',
    title: '一百个关注',
    text: '你 build in public 的账号粉丝数跳过了 100。',
    valence: 1,
    once: true,
    choices: [
      { text: '发条感谢推文', effects: [{ stat: 'mood', add: 4 }, { flag: 'audience', value: true }], resultText: '一百个人愿意看你搬砖。这就是最小可行的观众席。' },
    ],
  },
  {
    id: 'healthReport',
    pool: 'daily',
    title: '体检提醒',
    text: '手机弹出提醒：距离上次体检已经过去很久了。你揉了揉发酸的肩颈。',
    valence: 0,
    cooldown: 26,
    choices: [
      { text: '办张健身卡', effects: [{ stat: 'cash', add: -600 }, { stat: 'mood', add: 5 }], resultText: '每周三次，雷打不动。身体是独立开发者唯一的服务器。' },
      { text: '忙完这阵再说', effects: [{ stat: 'mood', add: -2 }], resultText: '「这阵」是个神奇的时间单位，它永远不会结束。' },
    ],
  },
  {
    id: 'powerOut',
    pool: 'daily',
    title: '停电了',
    text: '毫无预兆地停电，路由器和显示器同时熄灭。',
    valence: -1,
    cooldown: 28,
    choices: [
      { text: '用手机热点撑住', effects: [{ stat: 'mood', add: -2 }], resultText: '你举着手机找信号的样子，像极了荒岛求生。' },
    ],
  },
  {
    id: 'prMerged',
    pool: 'daily',
    title: 'PR 被合并了',
    text: '你给常用的开源库修的那个 bug，维护者今天合并了，还说了句 nice catch。',
    valence: 1,
    cooldown: 20,
    choices: [
      { text: '截图留念', effects: [{ stat: 'dev', add: 2 }, { stat: 'mood', add: 3 }], resultText: '全世界用这个库的人里，有一行代码是你的了。' },
    ],
  },
  {
    id: 'aiCrawler',
    pool: 'daily',
    title: 'AI 爬虫来了',
    text: '日志里出现大量 AI 公司的爬虫，流量统计好看了，服务器账单也好看了。',
    valence: 0,
    cooldown: 24,
    conditions: { flag: 'siteLive', is: true },
    choices: [
      { text: '屏蔽它们', effects: [{ stat: 'dev', add: 1 }], resultText: 'robots.txt 加了三行。时代的浪打过来，你先关好自家窗户。' },
      { text: '随它去，就当被引用', effects: [{ stat: 'cash', add: -60 }], resultText: '也许未来某个 AI 的回答里，有一句话是从你的站里学的。' },
    ],
  },
  {
    id: 'cleanRoom',
    pool: 'daily',
    title: '大扫除',
    text: '桌上的外卖盒和缠成一团的数据线，终于让你忍无可忍。',
    valence: 1,
    cooldown: 22,
    choices: [
      { text: '收拾一下午', effects: [{ stat: 'mood', add: 5 }], resultText: '房间清爽了，脑子好像也跟着清爽了。' },
    ],
  },
  {
    id: 'oldNotes',
    pool: 'daily',
    title: '三年前的笔记',
    text: '翻云盘时点开一篇三年前写的「我的人生规划」，里面写着：想做一个自己的产品。',
    valence: 1,
    once: true,
    conditions: { flag: 'siteLive', is: true },
    choices: [
      { text: '给当年的自己回个话', effects: [{ stat: 'mood', add: 6 }], resultText: '「嘿，我正在做了。」你在笔记末尾补了一行，落款是今天。' },
    ],
  },
  {
    id: 'anotherQuits',
    pool: 'daily',
    title: '又一个人下车了',
    text: '和你同期开始做站的网友宣布退坑："佛了，回去上班。"他做得其实不比你差。',
    valence: -1,
    cooldown: 26,
    choices: [
      { text: '给他留言祝好', effects: [{ stat: 'mood', add: -3 }], resultText: '这条路的残酷不在难，在长。祝他顺利，也祝自己熬得住。' },
      { text: '默默关掉页面，继续干活', effects: [{ stat: 'mood', add: -1 }, { stat: 'product', add: 1 }], resultText: '剩者为王这四个字，今天具体了一点。' },
    ],
  },
  {
    id: 'meditation',
    pool: 'daily',
    title: '睡前十分钟',
    text: '你试了试朋友安利的冥想 App，跟着呼吸了十分钟。',
    valence: 1,
    cooldown: 18,
    choices: [
      { text: '好像……有点用', effects: [{ stat: 'mood', add: 4 }], resultText: '焦虑没有消失，但它今晚睡在了隔壁房间。' },
    ],
  },

  // ---------- 命运 ----------
  {
    id: 'devConference',
    pool: 'fate',
    title: '大会门票',
    text: '一年一度的独立开发者大会开票了，票价加路费小一千五，嘉宾名单闪闪发光。',
    valence: 0,
    once: true,
    conditions: { turn: { gte: 8 } },
    choices: [
      { text: '去，见见世界', effects: [{ stat: 'cash', add: -1500 }, { stat: 'product', add: 4 }, { stat: 'mood', add: 6 }, { flag: 'network', value: true }], resultText: '两天听了十六场分享，加了一堆好友。回程高铁上，你的笔记本写满了。' },
      { text: '看线上回放就好', effects: [{ stat: 'mood', add: -1 }, { stat: 'product', add: 1 }], resultText: '回放三个月后才放出。你少花了一千五，也少了一屋子同路人。' },
    ],
  },
  {
    id: 'cloudPriceUp',
    pool: 'fate',
    title: '云厂商涨价',
    text: '邮件通知：你在用的服务全线涨价 25%，「为了提供更优质的服务」。',
    valence: -1,
    once: true,
    conditions: { flag: 'siteLive', is: true },
    choices: [
      { text: '认了，迁移成本更高', effects: [{ stat: 'cash', add: -300 }], resultText: '你在预算表上默默上调了一行。规模化之前，成本都是刀。' },
      { text: '周末大迁移', effects: [{ stat: 'mood', add: -4 }, { stat: 'dev', add: 3 }], resultText: '迁移文档写了四十步，踩坑十一个。但从此你不再怕任何厂商涨价。' },
    ],
  },
  {
    id: 'apiPaywalled',
    pool: 'fate',
    title: '免费 API 收费了',
    text: '你核心功能依赖的免费 API 突然宣布转为付费，宽限期两周。',
    valence: -1,
    once: true,
    conditions: { all: [{ flag: 'siteLive', is: true }, { stat: 'income', gte: 0.5 }] },
    choices: [
      { text: '付费，先保稳定', effects: [{ stat: 'cash', add: -500 }], resultText: '账单多了一行。你顺手把「减少外部依赖」写进了待办第一条。' },
      { text: '两周内自己造一个', effects: [{ stat: 'mood', add: -5 }, { stat: 'dev', add: 4 }, { stat: 'income', mul: 0.9 }], resultText: '肝了两周，功能弱一点但完全自主。有些独立，是被逼出来的。' },
    ],
  },
  {
    id: 'emoWeek',
    pool: 'fate',
    title: '情绪低谷',
    text: '没有具体原因，就是提不起劲。打开编辑器又关上，反复了一整周。',
    valence: -1,
    cooldown: 24,
    conditions: { stat: 'mood', lte: 50 },
    choices: [
      { text: '找朋友倾诉', effects: [{ stat: 'mood', add: 6 }], resultText: '朋友听完说：「你已经比大多数人勇敢了。」你没忍住红了眼眶。' },
      { text: '硬扛，用忙碌麻痹', effects: [{ stat: 'mood', add: -4 }, { stat: 'product', add: 2 }], resultText: '活儿干完了，心里的雾没散。下次别这样对自己。' },
    ],
  },
  {
    id: 'fakeNews',
    pool: 'fate',
    title: '群里的惊雷',
    text: '「Google 要对小站全面降权了！」截图在各个群里疯传，你的心提到了嗓子眼。',
    valence: 0,
    cooldown: 30,
    conditions: { flag: 'siteLive', is: true },
    choices: [
      { text: '找原始出处求证', effects: [{ stat: 'seo', add: 2 }, { stat: 'mood', add: 2 }], resultText: '查了半小时：断章取义的标题党。信息素养，是这个行业的免疫系统。' },
      { text: '跟着慌了一晚上', effects: [{ stat: 'mood', add: -5 }], resultText: '第二天官方辟谣了。你损失的只有一夜睡眠。' },
    ],
  },
  {
    id: 'diskCrash',
    pool: 'fate',
    title: '硬盘的遗言',
    text: '开机异响，然后是黑屏。你上一次备份是……你想不起来上一次备份是什么时候。',
    valence: -1,
    once: true,
    choices: [
      { text: '花钱做数据恢复', effects: [{ stat: 'cash', add: -1200 }, { stat: 'mood', add: -4 }], resultText: '恢复了九成。当晚你配好了三处自动备份，含泪写进开机脚本。' },
      { text: '认栽，凭记忆重写', effects: [{ stat: 'mood', add: -7 }, { stat: 'dev', add: 3 }], resultText: '重写的代码竟然比原来的干净。但这份「重构机会」，谁也不想再要第二次。' },
    ],
  },
  {
    id: 'fanLetter',
    pool: 'fate',
    title: '一封长信',
    text: '收件箱里躺着一封三千字的邮件，一位陌生用户细数你的产品怎样帮他度过了低谷。',
    valence: 1,
    once: true,
    conditions: { stat: 'income', gte: 1 },
    choices: [
      { text: '认真回了同样长的一封', effects: [{ stat: 'mood', add: 12 }], resultText: '你做的从来不只是一个网站。这封信你存进了「为什么出发」文件夹。' },
    ],
  },
  {
    id: 'cookieCompliance',
    pool: 'fate',
    title: '合规整改',
    text: '面向欧洲用户的站需要补全 Cookie 与隐私合规，条款读得你头皮发麻。',
    valence: -1,
    once: true,
    conditions: { stat: 'income', gte: 2 },
    choices: [
      { text: '认真做完整改', effects: [{ stat: 'mood', add: -3 }, { stat: 'product', add: 3 }], resultText: '弹窗上线，文档齐全。无聊的事做扎实，是长期生意的地基。' },
      { text: '先屏蔽欧洲流量', effects: [{ stat: 'income', mul: 0.9 }], resultText: '一刀切最省事，也切掉了一块市场。以后再回来捡。' },
    ],
  },
  {
    id: 'parentsBirthday',
    pool: 'fate',
    title: '爸的生日',
    text: '妈打电话：「你爸六十大寿，回来一趟吧。」你看了看日程表上密密麻麻的计划。',
    valence: 0,
    cooldown: 40,
    choices: [
      { text: '回家一周', effects: [{ stat: 'cash', add: -800 }, { stat: 'mood', add: 8 }], resultText: '饭桌上爸多喝了两杯，说「孩子干的是新行业」。你差点绷不住。' },
      { text: '寄了礼物，视频拜寿', effects: [{ stat: 'mood', add: -5 }], resultText: '视频里爸说没事忙你的。挂断后你对着屏幕坐了很久。' },
    ],
  },
  {
    id: 'contentStolen',
    pool: 'fate',
    title: '被搬运了',
    text: '你写的深度教程被某大号全文搬运，阅读量是你原帖的一百倍，没有署名。',
    valence: -1,
    once: true,
    conditions: { flag: 'audience', is: true },
    choices: [
      { text: '公开维权', effects: [{ stat: 'mood', add: -2 }, { flag: 'vocal', value: true }], resultText: '大号删稿道歉，围观群众顺着骂战找到了你——涨了一波粉，虽然过程窝火。' },
      { text: '在评论区留个链接', effects: [{ stat: 'mood', add: 1 }], resultText: '「原文在此。」四个字，体面且有效。' },
    ],
  },
  {
    id: 'taxSeason',
    pool: 'fate',
    title: '报税季',
    text: '境外收入怎么申报？你盯着税务 App，感觉自己看的是天书。',
    valence: -1,
    once: true,
    conditions: { stat: 'income', gte: 5 },
    choices: [
      { text: '花钱找专业代办', effects: [{ stat: 'cash', add: -1000 }], resultText: '专业的事给专业的人。你换回了一整周的专注和睡眠。' },
      { text: '自己啃政策', effects: [{ stat: 'mood', add: -5 }, { stat: 'product', add: 2 }], resultText: '啃了四个晚上终于办完。合规经营，睡得踏实。' },
    ],
  },
  {
    id: 'priceWar',
    pool: 'fate',
    title: '价格战',
    text: '主要竞品突然全线五折，你的转化肉眼可见地往下掉。',
    valence: -1,
    once: true,
    conditions: { stat: 'income', gte: 5 },
    choices: [
      { text: '跟降，守住份额', effects: [{ stat: 'income', mul: 0.75 }, { stat: 'mood', add: -4 }], resultText: '份额守住了，利润薄了。价格战没有赢家，只有活下来的人。' },
      { text: '不跟，做增值', effects: [{ stat: 'income', mul: 0.85 }, { stat: 'product', add: 4 }], resultText: '你把省下的精力堆在产品上。三个月后，对手的五折先撑不住了。' },
    ],
  },

  // ---------- 风口 ----------
  {
    id: 'googleShowcase',
    pool: 'wing',
    title: '官方的聚光灯',
    text: '搜索引擎官方博客正在筛选「优秀小型站点」案例，你的站进入了候选名单。',
    valence: 1,
    once: true,
    conditions: { all: [{ flag: 'siteLive', is: true }, { stat: 'income', gte: 3 }] },
    wingCatch: {
      conditions: { stat: 'product', gte: 60 },
      missText: '评审看了两分钟就划走了——内容不错，但产品还太糙。聚光灯只照向准备好的舞台。',
      missEffects: [{ stat: 'mood', add: -3 }],
    },
    choices: [
      { text: '接受案例采访', effects: [{ stat: 'income', mul: 1.6 }, { stat: 'mood', add: 10 }, { flag: 'famous', value: true }], resultText: '案例上线那天，你的站名出现在官方博客里。妈妈问你这个能打印出来吗。' },
    ],
  },
  {
    id: 'ossViral',
    pool: 'wing',
    title: '开源爆了',
    text: '你顺手开源的一个小工具被贴上了 HackerNews 首页，Star 数每刷新一次翻一倍。',
    valence: 1,
    once: true,
    conditions: { flag: 'siteLive', is: true },
    wingCatch: {
      conditions: { stat: 'dev', gte: 70 },
      missText: '流量涌进来的那两小时，你的代码里躺着一个高并发就崩的 bug。首页体验＝崩溃页面。热度来得快，去得更快。',
      missEffects: [{ stat: 'mood', add: -4 }, { stat: 'dev', add: 2 }],
    },
    choices: [
      { text: 'README 里放上主站链接', effects: [{ stat: 'income', add: 2, mul: 1.3 }, { stat: 'mood', add: 10 }, { flag: 'audience', value: true }], resultText: '开源是最长的长线钓鱼。Star 会凉，但搜索引擎记住了那些外链。' },
    ],
  },
]
