import type { EventCard } from '../../engine/types'

/** 角色专属事件线：不同人生的不同风景 */
export const characterEvents: EventCard[] = [
  // ---------- 宝妈 ----------
  {
    id: 'momKidFever',
    pool: 'fate',
    title: '半夜的额头',
    text: '凌晨两点，娃烧到 38.9°。你抱着他在儿科急诊坐到天亮，电脑里还开着没写完的页面。',
    valence: -1,
    cooldown: 26,
    characters: ['mom'],
    choices: [
      { text: '孩子第一，其他都能等', effects: [{ stat: 'cash', add: -400 }, { stat: 'mood', add: -5 }], resultText: '退烧后他在你怀里睡着了。那个没写完的页面，周末再说吧。' },
    ],
  },
  {
    id: 'momGoldenNight',
    pool: 'daily',
    title: '超长待机夜',
    text: '娃今晚八点半就睡熟了。整个客厅安静得能听到冰箱的嗡嗡声——全是你的时间。',
    valence: 1,
    cooldown: 14,
    characters: ['mom'],
    choices: [
      { text: '泡杯茶，开工', effects: [{ stat: 'product', add: 3 }, { stat: 'mood', add: 4 }], resultText: '三个小时高浓度专注。宝妈的深夜，一小时顶别人三小时。' },
      { text: '难得的夜，追一集剧', effects: [{ stat: 'mood', add: 6 }], resultText: '你值得。明天的键盘会感谢今晚充好电的你。' },
    ],
  },
  {
    id: 'momInlaw',
    pool: 'fate',
    title: '婆婆的关心',
    text: '「带好娃就行了，搞什么网站？又不挣钱。」婆婆一边择菜一边说，音量刚好全家都听得见。',
    valence: -1,
    cooldown: 30,
    characters: ['mom'],
    choices: [
      { text: '给她看这个月的收入', conditions: { stat: 'income', gte: 1 }, effects: [{ stat: 'mood', add: 6 }, { flag: 'familyKnows', value: true }], resultText: '「这是美金？」婆婆凑近屏幕看了很久，晚饭多给你盛了勺汤。' },
      { text: '笑笑，继续择菜', effects: [{ stat: 'mood', add: -6 }], resultText: '有些理解不必强求。你把委屈调成静音，像每一个普通的下午。' },
    ],
  },
  {
    id: 'momGroupBuy',
    pool: 'daily',
    title: '宝妈群的眼睛',
    text: '你在宝妈群里随口聊起做的工具，几个妈妈立刻问「在哪用？」——你突然意识到自己就在目标用户里。',
    valence: 1,
    once: true,
    characters: ['mom'],
    conditions: { flag: 'siteLive', is: true },
    choices: [
      { text: '认真收集她们的需求', effects: [{ stat: 'product', add: 4 }, { stat: 'income', add: 0.1 }, { flag: 'didResearch', value: true }], resultText: '十五条语音轰炸换来三个真需求。最好的用户调研，就在你的日常里。' },
    ],
  },
  {
    id: 'momHusbandHelp',
    pool: 'daily',
    title: '神队友上线',
    text: '周六早上，老公抱走娃：「今天我带，你去干你的大事业。」',
    valence: 1,
    cooldown: 20,
    characters: ['mom'],
    choices: [
      { text: '把这一天用到极致', effects: [{ stat: 'mood', add: 6 }, { stat: 'seo', add: 2 }], resultText: '整块的八小时，奢侈得像度假。晚上你给爷俩做了顿大餐。' },
    ],
  },
  {
    id: 'momKindergarten',
    pool: 'fate',
    title: '开学第一天',
    text: '娃背着小书包进了幼儿园。铁门关上，他哭了两声，你在门外站了十分钟。',
    valence: 1,
    once: true,
    characters: ['mom'],
    conditions: { turn: { gte: 30 } },
    choices: [
      { text: '眼泪擦掉，白天全是我的了', effects: [{ stat: 'mood', add: 8 }, { flag: 'kidInSchool', value: true }], resultText: '从今天起，每天多出六个小时。你的人生进度条，重新亮了起来。' },
    ],
  },

  // ---------- 学生党 ----------
  {
    id: 'stuFinals',
    pool: 'fate',
    title: '期末周',
    text: '四门考试排在同一周，而你的站正处在冲收录的关键期。',
    valence: -1,
    cooldown: 22,
    characters: ['student'],
    choices: [
      { text: '先保绩点，站放一放', effects: [{ stat: 'mood', add: -2 }, { stat: 'income', mul: 0.95 }], resultText: '考完最后一科走出教室，你第一件事是打开 Search Console。' },
      { text: '考试划水，肝站', effects: [{ stat: 'mood', add: -5 }, { stat: 'income', add: 0.2, mul: 1.05 }], resultText: '收录冲上去了，两门课擦线飘过。你安慰自己：学分和收入，都是学费。' },
    ],
  },
  {
    id: 'stuScholarship',
    pool: 'daily',
    title: '奖学金到账',
    text: '三等奖学金一千五到账。室友喊你请客，你脑子里闪过的是服务器续费页面。',
    valence: 1,
    cooldown: 40,
    characters: ['student'],
    choices: [
      { text: '一半请客，一半投项目', effects: [{ stat: 'cash', add: 1200 }, { stat: 'mood', add: 4 }], resultText: '烧烤摊上室友起哄让你讲讲「你那个网站」。你讲得眼睛发光。' },
    ],
  },
  {
    id: 'stuLibrary',
    pool: 'daily',
    title: '通宵自习室',
    text: '期中过后，通宵自习室空了大半。整层楼安静得像专门为你开的。',
    valence: 1,
    cooldown: 16,
    characters: ['student'],
    choices: [
      { text: '带上电脑进驻', effects: [{ stat: 'seo', add: 2 }, { stat: 'dev', add: 1 }], resultText: '在打瞌睡的考研人中间，你悄悄搭完了新的落地页。' },
    ],
  },
  {
    id: 'stuRoommates',
    pool: 'daily',
    title: '宿舍夜谈',
    text: '熄灯后，室友幽幽开口：「你天天鼓捣的那玩意儿，真能挣着钱？」',
    valence: 0,
    cooldown: 18,
    characters: ['student'],
    choices: [
      { text: '把后台数据给他们看', conditions: { stat: 'income', gt: 0 }, effects: [{ stat: 'mood', add: 5 }], resultText: '「卧槽，美金？！」那晚宿舍聊到两点，你多了三个免费测试员。' },
      { text: '「快了快了。」', effects: [{ stat: 'mood', add: -2 }], resultText: '黑暗里你自己也问了一遍自己：真能挣着钱吗？……能。你回答。' },
    ],
  },
  {
    id: 'stuProfessor',
    pool: 'fate',
    title: '导师的橄榄枝',
    text: '导师叫你进实验室帮他做项目，「对保研有好处」，但每周要占掉三个晚上。',
    valence: 0,
    once: true,
    characters: ['student'],
    choices: [
      { text: '答应，留条学术后路', effects: [{ stat: 'cash', add: 800 }, { stat: 'mood', add: -3 }, { stat: 'dev', add: 2 }], resultText: '实验室的活不难，就是琐碎。你在两条人生路上同时下注。' },
      { text: '婉拒，全押自己的站', effects: [{ stat: 'mood', add: 3 }, { flag: 'determined', value: true }], resultText: '导师愣了一下，说了句「年轻人有想法是好事」。门关上，你长出一口气。' },
    ],
  },
  {
    id: 'stuCompetition',
    pool: 'fate',
    title: '创业大赛',
    text: '学院转发了创业大赛通知，一等奖两万。你的站，好像刚好够格报个名。',
    valence: 1,
    once: true,
    characters: ['student'],
    conditions: { all: [{ flag: 'siteLive', is: true }, { turn: { gte: 15 } }] },
    choices: [
      { text: '报名，认真打磨路演', conditions: { stat: 'product', gte: 35 }, effects: [{ stat: 'cash', add: 5000 }, { stat: 'mood', add: 10 }, { stat: 'product', add: 3 }], resultText: '二等奖，五千块。评委说「数据是真的就很难得」。当然是真的——每一分都是。' },
      { text: '不去，比赛太虚', effects: [{ stat: 'mood', add: 1 }], resultText: '你选择把周末还给代码。路演 PPT 救不了产品，产品能救一切。' },
    ],
  },

  // ---------- 小城青年 ----------
  {
    id: 'townNobody',
    pool: 'daily',
    title: '无人区',
    text: '你想找个人聊聊「程序化 SEO」，通讯录翻到底，这座城市没有一个人知道你在说什么。',
    valence: -1,
    cooldown: 20,
    characters: ['smalltown'],
    choices: [
      { text: '把想说的写成帖子发出去', effects: [{ stat: 'mood', add: 2 }, { flag: 'audience', value: true }], resultText: '本地没有同类，但互联网上有。三条认真的回复，来自三个天南海北的县城。' },
      { text: '算了，孤独是标配', effects: [{ stat: 'mood', add: -3 }], resultText: '你合上手机。窗外的县城安静得听得见路灯的电流声。' },
    ],
  },
  {
    id: 'townInternet',
    pool: 'daily',
    title: '网又断了',
    text: '视频会议进行到一半，宽带毫无征兆地断了。这个月第三次。',
    valence: -1,
    cooldown: 22,
    characters: ['smalltown'],
    choices: [
      { text: '办第二条备用宽带', effects: [{ stat: 'cash', add: -300 }], resultText: '双线热备。你的机房条件终于赶上了你的野心。' },
    ],
  },
  {
    id: 'townCheapLife',
    pool: 'daily',
    title: '十二块的一天',
    text: '早餐三块，午饭六块，晚上妈喊你回家吃。今天总开销：十二块钱。',
    valence: 1,
    cooldown: 15,
    characters: ['smalltown'],
    choices: [
      { text: '这就是我的护城河', effects: [{ stat: 'mood', add: 4 }], resultText: '大城市的同行月烧一万五，你烧一千五。同样的收入，你能多熬十倍的时间。' },
    ],
  },
  {
    id: 'townBlindDate',
    pool: 'fate',
    title: '相亲局',
    text: '七大姑安排的相亲。对方开口第一句：「你做什么工作的？有编制吗？」',
    valence: -1,
    cooldown: 32,
    characters: ['smalltown'],
    choices: [
      { text: '认真解释什么是独立开发', effects: [{ stat: 'mood', add: -3 }], resultText: '你讲了十分钟，对方点点头：「哦，就是没工作。」这顿饭吃得很快。' },
      { text: '「我自己开公司的。」', effects: [{ stat: 'mood', add: 1 }], resultText: '也不算说谎。饭桌气氛好了很多，你在心里给自己的「公司」敬了杯茶。' },
    ],
  },
  {
    id: 'townFirstTalk',
    pool: 'fate',
    title: '县图书馆的讲台',
    text: '县图书馆搞「青年分享日」，管理员听说你「在网上挣外国人的钱」，想请你讲一场。',
    valence: 1,
    once: true,
    characters: ['smalltown'],
    conditions: { stat: 'income', gte: 1 },
    choices: [
      { text: '讲！讲给这座城听', effects: [{ stat: 'mood', add: 8 }, { flag: 'audience', value: true }], resultText: '台下坐了三十多人，有个高中生散场后追出来问了你八个问题。你看见了几年前的自己。' },
    ],
  },
  {
    id: 'townBigCityCall',
    pool: 'fate',
    title: '来大城市吧',
    text: '在深圳的发小打来电话：「过来吧，我给你内推，睡我客厅都行。这儿机会多。」',
    valence: 0,
    once: true,
    characters: ['smalltown'],
    conditions: { turn: { gte: 20 } },
    choices: [
      { text: '去看一圈再决定', effects: [{ stat: 'cash', add: -900 }, { stat: 'product', add: 3 }, { stat: 'seo', add: 2 }], resultText: '一周见了七个人，信息密度爆炸。回程你想通了：人可以回小城，认知不能。' },
      { text: '不去，我的战场在线上', effects: [{ stat: 'mood', add: 3 }, { flag: 'determined', value: true }], resultText: '「互联网是平的，兄弟。」你说完这句，发小笑骂了一句，说等你混出来请客。' },
    ],
  },

  // ---------- 角色专属质变链：岔路事件 ----------
  {
    id: 'momCommunityRise',
    pool: 'fate',
    title: '被推举的人',
    text: '宝妈群里你成了「懂行的那个」。三个群主拉了个联盟群，第一件事就是@你：「姐妹，你来牵头吧。」',
    valence: 1,
    once: true,
    characters: ['mom'],
    conditions: { all: [{ count: 'event.momGroupBuy', gte: 1 }, { stat: 'income', gte: 1 }, { turn: { gte: 30 } }] },
    choices: [
      {
        text: '接下来。妈妈们的需求我最懂',
        effects: [{ flag: 'momLeader', value: true }, { stat: 'income', add: 0.5 }, { stat: 'mood', add: 8 }],
        resultText: '你办起了社群周报，第一期就被转发了两百次。带娃人的时间是碎的，力量是整的。',
      },
      {
        text: '心力有限，婉拒',
        effects: [{ stat: 'mood', add: -2 }],
        resultText: '你退出了联盟群。有些机会放下也不可惜——你的主线始终是自己的站。',
      },
    ],
  },
  {
    id: 'stuGraduation',
    pool: 'fate',
    title: '毕业季',
    text: '答辩、散伙饭、招聘会同时涌来。辅导员追着问：「你的三方协议呢？」你默默打开了自己网站的后台。',
    valence: 0,
    once: true,
    characters: ['student'],
    conditions: { all: [{ flag: 'siteLive', is: true }, { turn: { gte: 55 } }] },
    choices: [
      {
        text: '把站写进简历，不投一份简历',
        conditions: { stat: 'income', gte: 3 },
        effects: [{ flag: 'gradFree', value: true }, { stat: 'mood', add: 10 }],
        resultText: '答辩台上你展示了自己的收入曲线，老师们问的问题比评委还多。你毕业了，雇主是你自己。',
      },
      {
        text: '先拿个 offer 保底，站继续做',
        effects: [{ stat: 'cash', add: 3000 }, { stat: 'mood', add: 2 }],
        resultText: '你签了个不坏的 offer。白天上班晚上做站——人生不是单选题。',
      },
    ],
  },
  {
    id: 'townApprentice',
    pool: 'fate',
    title: '追出来的高中生',
    text: '图书馆分享会上那个高中生又来了，这次他带着自己做的第一个网站，紧张得手心冒汗：「哥，你能带带我吗？」',
    valence: 1,
    once: true,
    characters: ['smalltown'],
    conditions: { all: [{ flag: 'audience', is: true }, { stat: 'income', gte: 5 }, { turn: { gte: 50 } }] },
    choices: [
      {
        text: '带。把这座城的火种点起来',
        effects: [{ flag: 'townMentor', value: true }, { stat: 'mood', add: 8 }],
        resultText: '你们约定每周六在图书馆碰头。半年后，县城有了第一个「站长角」。',
      },
      {
        text: '给他指条路，路要他自己走',
        effects: [{ stat: 'mood', add: 3 }],
        resultText: '你送了他一份自己整理的入门清单。有些帮助，点到为止才是尊重。',
      },
    ],
  },
]
